# Generated by Django 2.2.3 on 2019-10-04 16:46

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('status', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Project',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=64)),
                ('question', models.TextField()),
                ('ptype', models.CharField(choices=[('I', 'IKOSAEDER'), ('O', 'OKTAEDER')], max_length=32)),
                ('hasagenda', models.BooleanField(default=False)),
                ('admin', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Topic',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=128)),
                ('number', models.IntegerField()),
                ('desc', models.TextField()),
                ('color', models.CharField(default='', max_length=64)),
                ('agendanumber', models.IntegerField()),
                ('proj', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyka.Project')),
            ],
        ),
        migrations.CreateModel(
            name='Priority',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('priority', models.IntegerField(default=20)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyka.Member')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyka.Topic')),
            ],
        ),
        migrations.AddField(
            model_name='member',
            name='proj',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyka.Project'),
        ),
        migrations.CreateModel(
            name='Assignment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('atype', models.CharField(choices=[('M', 'MEMBER'), ('C', 'CRITIC')], max_length=16)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyka.Member')),
                ('topic', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cyka.Topic')),
            ],
        ),
    ]
