# Generated by Django 2.2.3 on 2019-10-04 18:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cyka', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='topic',
            name='agendanumber',
            field=models.IntegerField(null=True),
        ),
    ]
